<?php

namespace App\Console\Commands;

use App\Models\User;
use Illuminate\Console\Command;

class CreateAdminUser extends Command
{
    protected $signature = 'make:admin
        {--name= : Full name of the admin user}
        {--email= : Email address of the admin user}
        {--password= : Password for the admin user}
        {--role=admin : Role for the user (admin, manager, staff)}';

    protected $description = 'Create an admin user for the admin panel';

    public function handle(): int
    {
        $name = $this->option('name') ?? $this->ask('Full name');
        $email = $this->option('email') ?? $this->ask('Email address');
        $role = $this->option('role') ?? $this->choice('Role', ['admin', 'manager', 'staff'], 0);
        $password = $this->option('password') ?? $this->secret('Password (leave blank for auto-generated)');

        if (empty($password)) {
            $password = \Illuminate\Support\Str::password(12);
            $autoGenerated = true;
        } else {
            $autoGenerated = false;
        }

        if (User::where('email', $email)->exists()) {
            $this->error("A user with email '{$email}' already exists.");

            if (!$this->confirm('Do you want to update the existing user\'s role?', false)) {
                return Command::FAILURE;
            }

            $user = User::where('email', $email)->first();
            $user->update(['role' => $role]);

            if ($this->confirm('Update password?', false)) {
                $newPassword = $this->secret('New password');
                if (!empty($newPassword)) {
                    $user->update(['password' => bcrypt($newPassword)]);
                }
            }

            $this->info("User '{$email}' role updated to '{$role}'.");

            return Command::SUCCESS;
        }

        $user = User::create([
            'name' => $name,
            'email' => $email,
            'password' => bcrypt($password),
            'role' => $role,
            'email_verified_at' => now(),
        ]);

        $this->newLine();
        $this->info('╔══════════════════════════════════════════╗');
        $this->info('║       ADMIN USER CREATED SUCCESSFULLY    ║');
        $this->info('╚══════════════════════════════════════════╝');
        $this->newLine();
        $this->line("  Name:     {$user->name}");
        $this->line("  Email:    {$user->email}");
        $this->line("  Password: {$password}");
        $this->line("  Role:     {$role}");
        $this->newLine();
        $this->line("  Admin URL: " . url('/admin'));
        $this->newLine();

        if ($autoGenerated) {
            $this->warn('  ⚠  Password was auto-generated. Save it now.');
            $this->warn('     You will not be able to see it again.');
        }

        $this->newLine();

        return Command::SUCCESS;
    }
}
